# Generated by Django 2.2.5 on 2021-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210102_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
